name: Build And Test
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build_and_test:
    runs-on: windows-latest
    env:
      MAIN_SLN: Pinf.InstaService.Main.sln
      DEVOPS_SLN: Pinf.InstaService.DevOps.sln
      API_PROJ: Pinf.InstaService.API.InstaFetcher
      DEVOPS_EXEC: devops/DevOps.dll
    steps:
      - uses: actions/checkout@v2
      - name: Set project variables
        run: .\set_envs.bat
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies main
        run: dotnet restore ${{ env.MAIN_SLN }}
      - name: Build main
        run: dotnet build ${{ env.MAIN_SLN }} --no-restore
      - name: Test main
        run: dotnet test ${{ env.MAIN_SLN }} --no-build --verbosity normal
      - name: Restore dependencies devops
        run: dotnet restore ${{ env.DEVOPS_SLN }}
      - name: Build devops
        run: dotnet build ${{ env.DEVOPS_SLN }} --no-restore
      - name: Test devops
        run: dotnet test ${{ env.DEVOPS_SLN }} --no-build --verbosity normal