name: Close Server
on:
  schedule:
    - cron: "0 23 * * *"
jobs:
  close-server:
    runs-on: windows-latest
    env:
      AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_TOKEN: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SLN: Pinfluencer.SocialWrangler.DevOps.sln
      DEVOPS_EXEC: devops/DevOps.dll
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Close
        run: |
          dotnet publish ${{ env.DEVOPS_SLN }} -o devops
          dotnet exec ${{ env.DEVOPS_EXEC }} close