name: Deploy

on:
  release:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./Pinf.InstaService.API.InstaFetcher -c Release -o deploy
      - name: Add procfile
        run: |
          touch deploy/Procfile
          echo 'web: dotnet exec ./Pinf.InstaService.API.InstaFetcher.dll --urls http://0.0.0.0:5000/' >> deploy/Procfile
      - name: App settings variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'deploy/appsettings.Production.json'
        env:
          Auth0.Domain: ${{ secrets.AUTH0_DOMAIN }}
          Auth0.ManagementDomain: ${{ secrets.AUTH0_MANAGEMENT_DOMAIN }}
          Auth0.Id: ${{ secrets.AUTH0_ID }}
          Auth0.Secret: ${{ secrets.AUTH0_SECRET }}
          Simple-Auth-Key: ${{ secrets.SIMPLE_AUTH_KEY }}
      - name: Zip
        run: zip -r deploy.zip deploy
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Pinfluencer
          environment_name: Pinfluencer
          version_label: v1.0.0
          region: eu-west-2
          deployment_package: deploy.zip
        

