name: Deploy

on:
  release:
    branches: [ master ]
  push:
    branches: [ master, develop ]

jobs:
  compile-and-deploy:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ nodeploy ]')"
    env:
      AUTH0_ID: ${{ secrets.AUTH0_ID }}
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      SIMPLE_AUTH_KEY: ${{ secrets.SIMPLE_AUTH_KEY }}
      AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_TOKEN: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Deploy
        run: |
          dotnet publish Pinf.InstaService.API.InstaFetcher -o deploy -c Release
          touch deploy/Procfile
          echo 'pinf: dotnet exec ./Pinf.InstaService.API.InstaFetcher.dll --urls http://0.0.0.0:5100/' >> deploy/Procfile
          dotnet publish Pinf.InstaService.Bootstrapping.DevOps -o DevOps
          dotnet exec DevOps/DevOps.dll deploy
        

