name: Deploy Develop

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Get commit sha
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Publish production
        run: dotnet publish ./Pinf.InstaService.API.InstaFetcher -c Debug -o deploy
      - name: Add procfile
        run: |
          touch deploy/Procfile
          echo 'web: dotnet exec ./Pinf.InstaService.API.InstaFetcher.dll --urls http://0.0.0.0:5000/' >> deploy/Procfile
      - name: Add proof of domain ( for cert )
        run: |
          mkdir -p deploy/.well-known/pki-validation
          touch deploy/.well-known/pki-validation/BC074CC58368F01C6FB8CF426F41E3D1.txt
      - name: App settings variable substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'deploy/appsettings.json'
        env:
          Auth0.Domain: 'pinfluencer.eu.auth0.com'
          Auth0.ManagementDomain: 'https://pinfluencer.eu.auth0.com/api/v2/'
          Auth0.Id: ${{ secrets.AUTH0_ID }}
          Auth0.Secret: ${{ secrets.AUTH0_SECRET }}
          Simple-Auth-Key: ${{ secrets.SIMPLE_AUTH_KEY }}
      - name: Copy app settings for API
        run: |
          cd deploy
          mkdir api
          cp appsettings.json /api
      - name: Zip
        run: |
          cd deploy
          zip -r deploy.zip .
      - name: Deploy to development EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Pinfluencer
          environment_name: Pinfluencer-Dev
          version_label: ${{ steps.vars.outputs.sha_short }}-Dev
          region: eu-west-2
          deployment_package: deploy/deploy.zip
        

