name: Deploy
on:
  release:
    branches: [ master ]
  push:
    branches: [ master, develop ]
jobs:
  compile-and-deploy:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ nodeploy ]')"
    env:
      AUTH0_ID: ${{ secrets.AUTH0_ID }}
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      SIMPLE_AUTH_KEY: ${{ secrets.SIMPLE_AUTH_KEY }}
      AWS_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_TOKEN: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set project variables
        run: set_envs.bat
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Deploy
        run: |
          dotnet publish ${API_PROJ} -o deploy -c Release
          dotnet publish ${DEVOPS_SLN} -o devops
          dotnet exec ${DEVOPS_EXEC} deploy